spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
  liquibase:
    change-log: classpath:changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

jwt:
  expiration: 10m